remote_theme: rauldipeas/hacker
plugins:
- jekyll-remote-theme
title: Respin RDX
description:  Minha compilação pessoal do Ubuntu
favicon: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/32x32/apps/ubuntu-tweak.svg