name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          ./build.sh -
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kubuntu-rdx-from-scratch
          path: |
            scripts/kubuntu-rdx-from-scratch.iso
            scripts/image/md5sum.txt
