name: Kubuntu Deck Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build-kdeck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Kubuntu Deck Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: kubuntu
          FLAVOUR_NAME: Kubuntu Deck
          VERSION: 22.04.2
          CHROOT: respin-rdx/kdeck-chroot
          FLAVOUR_ID: KDeck
          ISO_NAME: kdeck
      - name: Envio dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: kdeck-respin-rdx
          path: /home/runner/work/respin-rdx/kdeck-respin-rdx.iso
      - name: Envio dos artefatos para o MEGA
        uses: Siege-Wizard/mega-upload@1.0.1
        with:
          file: /home/runner/work/respin-rdx/kdeck-respin-rdx.iso
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}