name: Kubuntu RDX
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash scripts/env.sh
      - name: Compilação do Kubuntu RDX
        run: |
          cd scripts
          ./build.sh -
      - name: Upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: kubuntu-rdx
          path: /home/runner/work/kubuntu-rdx/kubuntu-rdx/scripts/kubuntu-rdx.iso
      - name: Limpeza de logs antigos
        run: bash scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}      
