name: Neon Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Neon Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: neon
          FLAVOUR_NAME: Neon
          VERSION: 22.04.2
          CHROOT: respin-rdx/neon-chroot
          FLAVOUR_ID: Neon
          ISO_NAME: neon
      - name: Envio dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: neon-respin-rdx
          path: /home/runner/work/respin-rdx/neon-respin-rdx.iso
      - name: Envio de artefatos para o SFTP
        uses: betanzos/scp-upload@v1
        with:
          source: '/home/runner/work/respin-rdx/neon-respin-rdx.iso'
          host: ${{ secrets.SFTP_SERVER }}
          port: '22'
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY}}
          remote_dir: '/home/${{ secrets.SFTP_USER }}/respin-rdx/'
          recursive: 'false'
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}