name: Respin RDX
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
#      - name: Configuração do ambiente de compilação
#        run: bash scripts/env.sh
#      - name: Compilação do Ubuntu Respin RDX
#        run: bash -x scripts/build.sh
#        env:
#          CODENAME: jammy
#          FLAVOUR: ubuntu 
#          FLAVOUR_NAME: Ubuntu        
#      - name: Upload dos artefatos (Ubuntu)
#        uses: actions/upload-artifact@v3
#        with:
#          name: ubuntu-respin-rdx
#          path: /home/runner/work/respin-rdx/ubuntu-respin-rdx.iso
      - name: Compilação do Kubuntu Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: kubuntu 
          FLAVOUR_NAME: Kubuntu
      - name: Upload dos artefatos (Kubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: kubuntu-respin-rdx
          path: /home/runner/work/respin-rdx/kubuntu-respin-rdx.iso
      - name: Compilação do Xubuntu Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: xubuntu 
          FLAVOUR_NAME: Xubuntu
      - name: Upload dos artefatos (Xubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: xubuntu-respin-rdx
          path: /home/runner/work/respin-rdx/xubuntu-respin-rdx.iso          
      - name: Limpeza de logs antigos
        run: bash scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}