name: Ubuntu Cinnamon Lite Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Ubuntu Cinnamon Lite Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: ubuntu
          FLAVOUR_NAME: Ubuntu Cinnamon Lite
          VERSION: 22.04.2
          CHROOT: respin-rdx/ucl-chroot
          FLAVOUR_ID: UCL
          ISO_NAME: ucl
          IA_ACCESS: ${{ secrets.IA_ACCESS }}
          IA_SECRET: ${{ secrets.IA_SECRET }}
          IA_LOGGED_IN_USER: ${{ secrets.IA_LOGGED_IN_USER }}
          IA_LOGGED_IN_SIG: ${{ secrets.IA_LOGGED_IN_SIG }}
      - name: Upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: ucl-respin-rdx
          path: /home/runner/work/respin-rdx/ucl-respin-rdx.iso
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}