name: Ubuntu GNOME Lite Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build-ugl:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Ubuntu GNOME Lite Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: ubuntu
          FLAVOUR_NAME: Ubuntu GNOME Lite
          VERSION: 22.04.2
          CHROOT: respin-rdx/ugl-chroot
          FLAVOUR_ID: UGL
          ISO_NAME: ugl
      - name: Envio dos artefatos para o MEGA
        uses: Difegue/action-megacmd@master
        with:
          args: put /home/runner/work/respin-rdx/iso -c /respin-rdx/
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
      - name: Envio dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: ugl-respin-rdx
          path: /home/runner/work/respin-rdx/iso/ugl-respin-rdx.iso
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}