name: Xubuntu Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Xubuntu Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODENAME: jammy
          FLAVOUR: xubuntu
          FLAVOUR_NAME: Xubuntu
          VERSION: 22.04.2
          CHROOT: respin-rdx/xubuntu-chroot
          FLAVOUR_ID: Xubuntu
          ISO_NAME: xubuntu
      - name: Envio dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: xubuntu-respin-rdx
          path: /home/runner/work/respin-rdx/xubuntu-respin-rdx.iso
      - name: Envio de artefatos para o SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY}}
          port: 22
          uploads: |
            /home/runner/work/respin-rdx/kdeck-respin-rdx.iso => /home/${{ secrets.SFTP_USER }}/respin-rdx/
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}