name: Xubuntu Respin RDX
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'get-respin-rdx.sh'
      - 'upgrade-respin-rdx.sh'
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
jobs:
  build-xubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Configuração do ambiente de compilação
        run: bash -x scripts/env.sh
      - name: Compilação do Xubuntu Respin RDX
        run: bash -x scripts/build.sh
        env:
          CODEMANE: noble
          FLAVOUR: xubuntu
          FLAVOUR_NAME: Xubuntu
          VERSION: daily
          CHROOT: respin-rdx/xubuntu-chroot
          FLAVOUR_ID: Xubuntu
          ISO_NAME: xubuntu
      - name: Envio dos artefatos para o MEGA
        run: |
          mega-login ${{ secrets.MEGA_USERNAME }} ${{ secrets.MEGA_PASSWORD }}
          mega-put -c /home/runner/work/respin-rdx/iso/xubuntu-respin-rdx.iso /respin-rdx/
      - name: Envio dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: xubuntu-respin-rdx
          path: /home/runner/work/respin-rdx/iso/xubuntu-respin-rdx.iso
      - name: Limpeza de logs antigos
        run: bash -x scripts/actions-cleanup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}